const APPOINTMENT_STATUS = {
  REQUESTED: "REQUESTED",
  APPROVED: "APPROVED",
  BOOKED: "BOOKED",
  CHECKED_IN: "CHECKED_IN",
  SCREENING: "SCREENING",
  FAILED_SCREENING: "FAILED_SCREENING",
  DONATING: "DONATING",
  COMPLETED: "COMPLETED",
  NO_SHOW: "NO_SHOW",
  REJECTED: "REJECTED",
  CANCELLED: "CANCELLED",
};

const ACTIVE_APPOINTMENT_STATUSES = [
  APPOINTMENT_STATUS.REQUESTED,
  APPOINTMENT_STATUS.APPROVED,
  APPOINTMENT_STATUS.BOOKED,
  APPOINTMENT_STATUS.CHECKED_IN,
  APPOINTMENT_STATUS.SCREENING,
  APPOINTMENT_STATUS.DONATING,
];

const QR_ALLOWED_STATUSES = [
  APPOINTMENT_STATUS.APPROVED,
  APPOINTMENT_STATUS.BOOKED,
  APPOINTMENT_STATUS.CHECKED_IN,
];

const DONATION_ALLOWED_STATUSES = [
  APPOINTMENT_STATUS.APPROVED,
  APPOINTMENT_STATUS.BOOKED,
  APPOINTMENT_STATUS.CHECKED_IN,
  APPOINTMENT_STATUS.SCREENING,
  APPOINTMENT_STATUS.DONATING,
];

module.exports = {
  APPOINTMENT_STATUS,
  ACTIVE_APPOINTMENT_STATUSES,
  QR_ALLOWED_STATUSES,
  DONATION_ALLOWED_STATUSES,
};